#!/bin/bash
nkf -e test_all.log | mymkhyp.pl -p 2 >test_all.hyp
nkf -e test_clean.log | mymkhyp.pl -p 2 >test_clean.hyp
nkf -e test_expressway_snr-5.log | mymkhyp.pl -p 2 >test_expressway_snr-5.hyp
nkf -e test_expressway_snr0.log | mymkhyp.pl -p 2 >test_expressway_snr0.hyp
nkf -e test_expressway_snr5.log | mymkhyp.pl -p 2 >test_expressway_snr5.hyp
nkf -e test_expressway_snr10.log | mymkhyp.pl -p 2 >test_expressway_snr10.hyp
nkf -e test_expressway_snr15.log | mymkhyp.pl -p 2 >test_expressway_snr15.hyp
nkf -e test_expressway_snr20.log | mymkhyp.pl -p 2 >test_expressway_snr20.hyp
nkf -e test_cityroad_snr-5.log | mymkhyp.pl -p 2 >test_cityroad_snr-5.hyp
nkf -e test_cityroad_snr0.log | mymkhyp.pl -p 2 >test_cityroad_snr0.hyp
nkf -e test_cityroad_snr5.log | mymkhyp.pl -p 2 >test_cityroad_snr5.hyp
nkf -e test_cityroad_snr10.log | mymkhyp.pl -p 2 >test_cityroad_snr10.hyp
nkf -e test_cityroad_snr15.log | mymkhyp.pl -p 2 >test_cityroad_snr15.hyp
nkf -e test_cityroad_snr20.log | mymkhyp.pl -p 2 >test_cityroad_snr20.hyp
nkf -e test_audio_snr-5.log | mymkhyp.pl -p 2 >test_audio_snr-5.hyp
nkf -e test_audio_snr0.log | mymkhyp.pl -p 2 >test_audio_snr0.hyp
nkf -e test_audio_snr5.log | mymkhyp.pl -p 2 >test_audio_snr5.hyp
nkf -e test_audio_snr10.log | mymkhyp.pl -p 2 >test_audio_snr10.hyp
nkf -e test_audio_snr15.log | mymkhyp.pl -p 2 >test_audio_snr15.hyp
nkf -e test_audio_snr20.log | mymkhyp.pl -p 2 >test_audio_snr20.hyp
nkf -e test_audio-expressway_snr-5.log | mymkhyp.pl -p 2 >test_audio-expressway_snr-5.hyp
nkf -e test_audio-expressway_snr0.log | mymkhyp.pl -p 2 >test_audio-expressway_snr0.hyp
nkf -e test_audio-expressway_snr5.log | mymkhyp.pl -p 2 >test_audio-expressway_snr5.hyp
nkf -e test_audio-expressway_snr10.log | mymkhyp.pl -p 2 >test_audio-expressway_snr10.hyp
nkf -e test_audio-expressway_snr15.log | mymkhyp.pl -p 2 >test_audio-expressway_snr15.hyp
nkf -e test_audio-expressway_snr20.log | mymkhyp.pl -p 2 >test_audio-expressway_snr20.hyp
nkf -e test_audio-cityroad_snr-5.log | mymkhyp.pl -p 2 >test_audio-cityroad_snr-5.hyp
nkf -e test_audio-cityroad_snr0.log | mymkhyp.pl -p 2 >test_audio-cityroad_snr0.hyp
nkf -e test_audio-cityroad_snr5.log | mymkhyp.pl -p 2 >test_audio-cityroad_snr5.hyp
nkf -e test_audio-cityroad_snr10.log | mymkhyp.pl -p 2 >test_audio-cityroad_snr10.hyp
nkf -e test_audio-cityroad_snr15.log | mymkhyp.pl -p 2 >test_audio-cityroad_snr15.hyp
nkf -e test_audio-cityroad_snr20.log | mymkhyp.pl -p 2 >test_audio-cityroad_snr20.hyp