#!/bin/bash
./avrec_all.sh
./avrec_clean.sh
./avrec_expressway_snr-5.sh
./avrec_expressway_snr0.sh
./avrec_expressway_snr5.sh
./avrec_expressway_snr10.sh
./avrec_expressway_snr15.sh
./avrec_expressway_snr20.sh
./avrec_cityroad_snr-5.sh
./avrec_cityroad_snr0.sh
./avrec_cityroad_snr5.sh
./avrec_cityroad_snr10.sh
./avrec_cityroad_snr15.sh
./avrec_cityroad_snr20.sh
./avrec_audio_snr-5.sh
./avrec_audio_snr0.sh
./avrec_audio_snr5.sh
./avrec_audio_snr10.sh
./avrec_audio_snr15.sh
./avrec_audio_snr20.sh
./avrec_audio-expressway_snr-5.sh
./avrec_audio-expressway_snr0.sh
./avrec_audio-expressway_snr5.sh
./avrec_audio-expressway_snr10.sh
./avrec_audio-expressway_snr15.sh
./avrec_audio-expressway_snr20.sh
./avrec_audio-cityroad_snr-5.sh
./avrec_audio-cityroad_snr0.sh
./avrec_audio-cityroad_snr5.sh
./avrec_audio-cityroad_snr10.sh
./avrec_audio-cityroad_snr15.sh
./avrec_audio-cityroad_snr20.sh
