#!/bin/bash
./mfcpcarec_all.sh
./mfcpcarec_clean.sh
./mfcpcarec_expressway_snr-5.sh
./mfcpcarec_expressway_snr0.sh
./mfcpcarec_expressway_snr5.sh
./mfcpcarec_expressway_snr10.sh
./mfcpcarec_expressway_snr15.sh
./mfcpcarec_expressway_snr20.sh
./mfcpcarec_cityroad_snr-5.sh
./mfcpcarec_cityroad_snr0.sh
./mfcpcarec_cityroad_snr5.sh
./mfcpcarec_cityroad_snr10.sh
./mfcpcarec_cityroad_snr15.sh
./mfcpcarec_cityroad_snr20.sh
./mfcpcarec_audio_snr-5.sh
./mfcpcarec_audio_snr0.sh
./mfcpcarec_audio_snr5.sh
./mfcpcarec_audio_snr10.sh
./mfcpcarec_audio_snr15.sh
./mfcpcarec_audio_snr20.sh
./mfcpcarec_audio-expressway_snr-5.sh
./mfcpcarec_audio-expressway_snr0.sh
./mfcpcarec_audio-expressway_snr5.sh
./mfcpcarec_audio-expressway_snr10.sh
./mfcpcarec_audio-expressway_snr15.sh
./mfcpcarec_audio-expressway_snr20.sh
./mfcpcarec_audio-cityroad_snr-5.sh
./mfcpcarec_audio-cityroad_snr0.sh
./mfcpcarec_audio-cityroad_snr5.sh
./mfcpcarec_audio-cityroad_snr10.sh
./mfcpcarec_audio-cityroad_snr15.sh
./mfcpcarec_audio-cityroad_snr20.sh
