#!/bin/bash
./probrec_all.sh
./probrec_clean.sh
./probrec_expressway_snr-5.sh
./probrec_expressway_snr0.sh
./probrec_expressway_snr5.sh
./probrec_expressway_snr10.sh
./probrec_expressway_snr15.sh
./probrec_expressway_snr20.sh
./probrec_cityroad_snr-5.sh
./probrec_cityroad_snr0.sh
./probrec_cityroad_snr5.sh
./probrec_cityroad_snr10.sh
./probrec_cityroad_snr15.sh
./probrec_cityroad_snr20.sh
./probrec_audio_snr-5.sh
./probrec_audio_snr0.sh
./probrec_audio_snr5.sh
./probrec_audio_snr10.sh
./probrec_audio_snr15.sh
./probrec_audio_snr20.sh
./probrec_audio-expressway_snr-5.sh
./probrec_audio-expressway_snr0.sh
./probrec_audio-expressway_snr5.sh
./probrec_audio-expressway_snr10.sh
./probrec_audio-expressway_snr15.sh
./probrec_audio-expressway_snr20.sh
./probrec_audio-cityroad_snr-5.sh
./probrec_audio-cityroad_snr0.sh
./probrec_audio-cityroad_snr5.sh
./probrec_audio-cityroad_snr10.sh
./probrec_audio-cityroad_snr15.sh
./probrec_audio-cityroad_snr20.sh
