#!/bin/bash
./dbnfrec_all.sh
./dbnfrec_clean.sh
./dbnfrec_expressway_snr-5.sh
./dbnfrec_expressway_snr0.sh
./dbnfrec_expressway_snr5.sh
./dbnfrec_expressway_snr10.sh
./dbnfrec_expressway_snr15.sh
./dbnfrec_expressway_snr20.sh
./dbnfrec_cityroad_snr-5.sh
./dbnfrec_cityroad_snr0.sh
./dbnfrec_cityroad_snr5.sh
./dbnfrec_cityroad_snr10.sh
./dbnfrec_cityroad_snr15.sh
./dbnfrec_cityroad_snr20.sh
./dbnfrec_audio_snr-5.sh
./dbnfrec_audio_snr0.sh
./dbnfrec_audio_snr5.sh
./dbnfrec_audio_snr10.sh
./dbnfrec_audio_snr15.sh
./dbnfrec_audio_snr20.sh
./dbnfrec_audio-expressway_snr-5.sh
./dbnfrec_audio-expressway_snr0.sh
./dbnfrec_audio-expressway_snr5.sh
./dbnfrec_audio-expressway_snr10.sh
./dbnfrec_audio-expressway_snr15.sh
./dbnfrec_audio-expressway_snr20.sh
./dbnfrec_audio-cityroad_snr-5.sh
./dbnfrec_audio-cityroad_snr0.sh
./dbnfrec_audio-cityroad_snr5.sh
./dbnfrec_audio-cityroad_snr10.sh
./dbnfrec_audio-cityroad_snr15.sh
./dbnfrec_audio-cityroad_snr20.sh
